hiscoder-com/level

.eslintrc.json, .prettierrc, .vscode/extensions.json, .vscode/settings.json, next.config.js, package.json, pages/index.js, yarn.lock
=> Setup eslint and prettier

.eslintrc.json, components/footer.js
plus some changes in eslintrc.json to allow babel work properly
Так как у меня не было разрешения на доступ, пришлось сперва Fork запросить, и потом только смог сделать pull request.
=> Fixed disabled Button functionality

components/AppBar.js, components/SideBar.js, components/SideBarLink.js, components/layout.js, pages/agreements_text.js, styles/globals.css
- Избавился от многих лишних вещей/классов.
- Почти все ссылки вынес в отдельный компонент SideBarLink с возможностью передачи через пропсы всей необходимой информации. 
- Сгруппировал несколько классов для удобства в индивидуальные классы
=> WIP on sidebar

components/SideBar.js, components/layout.js
- на маленьком экране разрешение до 640px - сайдбар раскрывается на полную ширину и цвет фона без эффекта прозрачности
- на больших экранах - ширина, которая была установлена как в макете и с полупрозрачностью
=> sidebar small/large screen adjustments WIP

pages/confession-steps.js, styles/globals.css
- Все в принципе настроил так же как и было на скриншоте в Issue #73 
- Вернул стили стрелок переключения карточек, то есть они стали такими же как и были прежде на большом экране.
- Что касается padding внутри карточки, поигрался с меньшими значениями но из-за точек в списках, смотрелось уже совсем уж прижато к стенке, поэтому оставил таким какое есть сейчас.
=> Feature artyom 73 - steps of faith #73

components/Timer.js, styles/globals.css
.../steps/1
-  Если таймер запущен, мигает разделитель между минутами и секундами;
-  При запуске таймера исключена задержка 1 сек
=> Fix Timer Component 

components/Avatars.js, components/Projects.js, components/TImage.js, components/TranslatorImage.js, components/Translators.js, styles/globals.css
/languages/ru
компонент отображает:
-  заголовок проекта
-  язык
-  прогресс
-  переводчиков, работающих над проектом
переводчики:
отдельный компонент, отображает аватар, если есть в БД, 
иначе отображает SVG с первыми двумя буквами логина user`а
=> Avatars component

components/VerseDivider.js, pages/projects/[code]/books/[bookid]/[chapterid].js, schema.sql
Changes:
1.Added 2 columns with type 'timestamp' in table chapters: 'started_at' and 'finished_at'
2. Added rpc functions   for update chapters.started_at
```
let { data, error } = await supabase
.rpc('start_chapter', {
chapter_id, 
project_id
})
if (error) console.error(error)
else console.log(data)
```
3. Rename VerseDistributor in VerseDivider
4. Added btn class to buttons
=> Add rpc function start_chapter

components/Panel/Resources/Bible.js, components/Panel/Resources/TNTWL.js, components/ProjectEdit.js, pages/api/git/bible.js, pages/api/git/obs-tn.js, pages/api/git/tn.js, utils/tsvHelper.js
переписал немного, если норм, тогда поправлю также obs-tn и tw, obs-tw прямо в этой ветке
=> Fix TN and Bible

components/Panel/Helpers/BlindEditor.js, components/Panel/Helpers/PersonalNotes.js, components/Panel/Helpers/TeamNotes.js, package.json, pages/api/personal_notes/index.js, public/locales/ru/common.json, styles/globals.css, tailwind.config.js, yarn.lock
Добавил удаление всех заметок в личные заметки и модалку с вопросом - `вы точно хотите удалить?`.
=> Add question-modal for delete notes

components/Panel/Resources/TWL.js, pages/api/git/obs-tn.js, pages/api/git/obs-tq.js, pages/api/git/obs-twl.js, pages/api/git/obs.js, pages/api/git/tn.js, pages/api/git/tq.js, pages/api/git/twl.js, public/locales/ru/common.json
Отображаются все ноутся и вордсы на шагах, где должны отображаться только определенные
=> Hot fix 221

components/Panel/Resources/Bible.js, components/Panel/Resources/TN.js, components/Panel/Resources/TQ.js, components/Panel/Resources/TWL.js, components/Panel/Tool.js, components/Workspace.js, pages/api/git/twl.js, pages/translate/[project]/[book]/[chapter]/[step]/index.js, utils/hooks.js
Добавлено запоминание скролла по клику на элемент списка.
Выделено подчеркиванием  последний нажатый элемент списка
=> Added scroll in panel tools

components/Footer.js, components/MarkdownExtended.js, components/Panel/Resources/TN.js, components/Panel/Resources/TWL.js, components/Panel/UI/TNTWLContent.js, components/Project.js, components/SideBar.js, components/SwitchLocalization.js, links.md, pages/api/git/tn.js, pages/index.js, pages/projects/[code]/books/[bookid]/[chapterid].js, pages/projects/[code]/index.js, pages/translate/[project]/[book]/[chapter]/[step]/[translator].js, utils/helper.js, utils/usfmHelper.js
1. Поправлены переводы
2. Если нет названия TN, тогда выводить OrigQuote
3. Убрать лишнее в sideMenu
4. Добавить смену локализации в side menu
5. Синхронизирован показ даты с локалью
6. Из выбора книг убрано frt
7. убрано undefined из Bible
=> Fixes UI and bugs

components/Panel/Helpers/Dictionary.js, components/Workspace.js, schema.sql
Поменял цвет выделения буквенного ряда на серый, как в Писании и на слова тоже
Надписи и иконки надо немного выше поднял.
Если добавить Адам и апельсин  - то в буквенном ряде будет А и а. Это исправил. Добавляется только заглавная или исправляется на заглавную, а потом добавляется
При создании таблицы projects - в колонке dictionaries_alphabet создаю по-умолчанию пустой массив
в буквенном ряде не сразу появлялся новый символ- исправил
=> Fix some changes in UI of dictionary

components/ProjectCard.js
=> fixed a broken brief

components/Account.js, components/BriefResume.js, components/Login.js, components/SideBar.js, pages/404.js, pages/agreements.js, pages/confession-steps.js, pages/confession.js, pages/languages/[lang].js, pages/projects/[code]/books/[bookid]/[chapterid].js, pages/projects/[code]/books/index.js, pages/projects/[code]/edit/brief/index.js, pages/projects/[code]/edit/index.js, pages/projects/[code]/edit/settings.js, pages/projects/[code]/index.js, pages/projects/create.js, pages/translate/[project]/[book]/[chapter]/[step]/[translator].js, pages/translate/[project]/[book]/[chapter]/[step]/index.js, pages/translate/[project]/[book]/[chapter]/[step]/intro.js, pages/user-agreement.js
1. Removed 1 query to db.
2. Fixed error with Sign out
=> Remove 1 query from db, fix signout

components/Recorder.js, public/pause.svg, public/play.svg
replaced audio component with play button
closed #308
=> feat: :sparkles: modified audio component

components/Panel/Helpers/BlindEditor.js, components/Panel/Helpers/CommandEditor.js, components/Panel/Helpers/Editor.js, pages/projects/[code]/books/[bookid]/[chapterid].js, public/locales/en/common.json
=> Add toast to incorrect save verses

components/Panel/Resources/TWL.js
increased the maximum cache time for TW
=> fix: :bug: get high max age of cache in TW

components/Panel/Resources/TWL.js, pages/api/git/tw.js, utils/apiHelper.js, utils/helper.js
Rewrite to a fetching TW in zip file
=> Fix valyukhov 147

components/Panel/Resources/OBSTN.js
Didn't work auto scroll in OBS TN - it fixed issue
=> fix: :bug: fix scroll in OBSTN

components/Panel/Resources/TN.js, yarn.lock
Add parameters to fix loading TN
=> fix: :bug: fix loading in TN

components/Panel/Helpers/Dictionary.js, components/Panel/Helpers/PersonalNotes.js, components/Panel/Helpers/TeamNotes.js, components/Panel/UI/TNTWLContent.js, components/SwitchLocalization.js
1) fixing arrow to TNTWLContent
2) bringing the "Back" button to a general form
3) fixed a bug with displaying a list of languages in the SwitchLocalization component
=> fixing arrow to TNTWLContent

components/ProjectEdit/ResourceSettings.js, utils/helper.js
Now we use the URL without SRC
=> Create one standart url to parse

components/ProjectPersonalCard.js
icon read mode near name project
reading mode is displayed if the project has translated verses.
=> Icon for reader mode denis arger 507

components/Panel/Helpers/PersonalNotes.js, components/Panel/Helpers/TeamNotes.js, package.json, yarn.lock
1) Set up clicks so that one click opens a note/folder, two clicks open the entire tree, and three clicks start renaming
2) added search by notes
3) fixed bug with open context menu
=> personal notes and team notes: click processing

.github/workflows/ci.yaml, .github/workflows/production.yaml, .github/workflows/staging.yaml, supabase/.gitignore, supabase/config.toml, supabase/migrations/20240313204519_remote_schema.sql
Setup for actions github with supabase cli
https://supabase.com/docs/guides/cli/managing-environments
=> Setup actions for supabase cli

components/Project/ChapterList/ChapterMobileMenu.js, components/Project/ChapterList/ChapterProgressControls.js, components/Project/ChapterList/ProjectParticipants.js, components/Project/ChapterList/VerseDistributionButtons.js, pages/projects/[code]/books/[bookid]/[chapterid].js, public/locales/en/chapters.json
The "Select all" and "Deselect" buttons were added and the corresponding functionality of these buttons was configured.
For better readability, maintainability, and scalability of the code, the ChapterVersesPage has separated the code into separate components with clearly defined responsibilities, following the principle of separation of concerns:
- ChapterMobileMenu
- ChapterProgressControls
- ProjectParticipants
- VerseDistributionButtons
The ChapterMobileMenu component is a drop-down mobile menu that allows you to manage project participants, distribute verses between translators, and monitor the progress of work on a chapter.
The ChapterProgressControls component is responsible for displaying and handling buttons for starting, finishing, and canceling a chapter. It communicates with …
=> Make the "Select all" and "Deselect" buttons & refactoring ChapterVersesPage

README.md, components/Panel/Helpers/BlindEditor.js, components/ProjectCard.js, components/ProjectPersonalCard.js, supabase/.gitignore, supabase/seed.sql
Added instruction for installation
=> Fix readme

components/Footer.js, components/TranslatorImage.js, components/Translators.js, pages/translate/[project]/[book]/[chapter]/[step]/index.js, supabase/migrations/20240622142654_add_function_get_active_translators.sql
Fix component Translators for big count of user
=> Hot fix big count translators

components/Project/Download.js
1. Add titles for resources.
2. Add name of zip.
3. Add name of book.
4.Add Project code
=> Add changes to create project for desktop

components/BasicInformation.js, components/LanguageCreate.js, components/UpdateField.js
When open steps - page not breaks.
=> Fix bug breaks steps
